### PR TITLE
Setting-panel CSS fixes

### PR DESCRIPTION
**Pull request by amirhp-com**
- [x] saving setting will break the layout
- [x] fix toggle handle vertical position
- [x] change h2 font to Tahoma

before|after
| --- | --- |
|shot-1|shot-2|
||

### CODE REVIEW

**Comment by man4toman** [comment]
Thanks @amirhp-com 
Your PR have been merged to the project.

**Comment by amirhp-com** [comment]
> Thanks @amirhp-com Your PR have been merged to the project.

Thanks, Morteza, what should I do to be among contributors of this plugin in w.org?

**Comment by man4toman** [comment]
For that, you need to be a component maintainer or new feature provider.
Every contributor of ParsiDate commit us like that. (for example add WooCommerce Gateways).

**Comment by amirhp-com** [comment]
Thank you very much, do you have any suggestion for a new feature?

**Pull request merged**
