### PR TITLE
WPML Support

### PR DESCRIPTION
**Pull request by khalilifar**
Please accept this pull request as every time there is a  plugin update other languages of website break and I have to overwrite these 2 files manually each time.

### CODE REVIEW

**Comment by mostafasoufi** [comment]
Dear @man4toman or @parsa-kafi,

Please check this merge request.

**Comment by khalilifar** [comment]
Wow that was quick. I thought I have to check back in a few weeks :)

**Comment by parsakafi** [comment]
Hi MR. @khalilifar 
Your change made problem when locale different with "fa_IR" and use jalali date

**Comment by khalilifar** [comment]
@parsa-kafi 
Well what  do you suggest we do ?

Can you add an option in settings page or a hook we can add to functions.php of a theme to  select list of locales that jalali date is applied to ?

So we don't have jalali date in english version of the website.

This change solves my problem but yeah there might be some cases who need jalali date on other locales too.

**Comment by khalilifar** [comment]
@parsa-kafi hey so I searched around couldn't find any other countries who use jalali date beside iran, so I don't think it's needed for any other locales really.

There was also some conflicts as my changes was committed on an older version which I had them fixed 
It's working on live websites now without problem. like drtaherian.com drdarvishpour.com
If you could merge this or at least give an option or hook if you really want to allow for other locales to use jalali date as well.
Thanks a lot

**Comment by mostafasoufi** [comment]
This issue is waiting?

**Comment by khalilifar** [comment]
@mostafasoufi nobody answering anymore, right now I am using my own fork as I can't use this plugin in any multilingual website

**Comment by parsakafi** [comment]
new version 2.3.2 fixed this bug

**Comment by khalilifar** [comment]
@parsa-kafi  Not fixed, you have to remove the filters too when language is not persian,
I updated one of the websites problem is still there.
capture
Your update  is kind of my change, but about half of it. why not just merge the pull request ? it's tested and it's working.

**Comment by parsakafi** [comment]
Check last committed version with default WordPress theme and custom theme ,@khalilifar

**Pull request closed without merging**
